// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-qMEDWegThDEVPJr7-5UiVGMTH3Q4IWo',
    appId: '1:206739211715:web:b396117ebe9a1154a42976',
    messagingSenderId: '206739211715',
    projectId: 'chat-app-a46d6',
    authDomain: 'chat-app-a46d6.firebaseapp.com',
    storageBucket: 'chat-app-a46d6.appspot.com',
    measurementId: 'G-350XGX3YCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcET3TLtXNxurjA3N2at2MrvwPScL9c3s',
    appId: '1:206739211715:android:fcc4942484eb81fea42976',
    messagingSenderId: '206739211715',
    projectId: 'chat-app-a46d6',
    storageBucket: 'chat-app-a46d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuSSe9fX9aXzxyvLiGW-66KbBU3vpcuEg',
    appId: '1:206739211715:ios:589fa33e933a7764a42976',
    messagingSenderId: '206739211715',
    projectId: 'chat-app-a46d6',
    storageBucket: 'chat-app-a46d6.appspot.com',
    iosClientId: '206739211715-8fq694t4vnriqsilsqd7m6pn5hqmfakm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
